"""Initial migration.

Revision ID: 08c4316ae003
Revises: 
Create Date: 2020-07-25 15:00:12.858453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08c4316ae003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid', name='users_pkey')
    )
    op.create_table('posts',
    sa.Column('pid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createtime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.uid'], name='posts_author_fkey'),
    sa.PrimaryKeyConstraint('pid', name='posts_pkey')
    )
    # ### end Alembic commands ###
